# Generated by Django 2.0.5 on 2018-05-15 23:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Circle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('purpose', models.TextField(max_length=600)),
                ('strategies', models.TextField(max_length=600)),
                ('domains', models.TextField(max_length=600)),
                ('policies', models.TextField(max_length=600)),
                ('accountabilities', models.TextField(max_length=600)),
                ('objectives', models.TextField(max_length=600)),
                ('metrics', models.TextField(max_length=600)),
                ('birthdate', models.DateTimeField()),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('reports', models.TextField(max_length=600)),
                ('crosslinks', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cross_link', to=settings.AUTH_USER_MODEL)),
                ('facilitator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fac_link', to=settings.AUTH_USER_MODEL)),
                ('leadlink', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lead_link', to=settings.AUTH_USER_MODEL)),
                ('replink', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rep_link', to=settings.AUTH_USER_MODEL)),
                ('secretary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sec_link', to=settings.AUTH_USER_MODEL)),
                ('supercircle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='managetime.Circle')),
            ],
        ),
        migrations.CreateModel(
            name='MemberCommitment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=600)),
                ('nextaction', models.TextField(max_length=600)),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField()),
                ('status', models.CharField(max_length=60)),
                ('value', models.CharField(max_length=30)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('description', models.TextField(max_length=1000)),
                ('startdate', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField(auto_now_add=True)),
                ('objectives', models.TextField(max_length=1000)),
                ('keyresults', models.TextField(max_length=600)),
                ('status', models.TextField(max_length=600)),
                ('weeklyreport', models.TextField(max_length=600)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('circle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='managetime.Circle')),
                ('projectlead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('purpose', models.TextField(max_length=600)),
                ('domains', models.TextField(max_length=600)),
                ('accountabilities', models.TextField(max_length=600)),
                ('successindicators', models.TextField(max_length=600)),
                ('projectcircle', models.TextField(max_length=60)),
                ('birthdate', models.DateTimeField()),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('montlyreport', models.TextField(max_length=600)),
                ('collaboartors', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='managetime.Role')),
                ('energizers', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RoleCommitment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=600)),
                ('nextaction', models.TextField(max_length=600)),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField()),
                ('status', models.CharField(max_length=60)),
                ('value', models.CharField(max_length=30)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=30)),
                ('last_update', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(max_length=600)),
                ('startdate', models.DateTimeField(auto_now_add=True)),
                ('deadline', models.DateTimeField()),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='managetime.Project')),
            ],
        ),
        migrations.AddField(
            model_name='rolecommitment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='managetime.Task'),
        ),
        migrations.AddField(
            model_name='membercommitment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='managetime.Task'),
        ),
    ]
