# Generated by Django 2.0.5 on 2018-05-18 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managetime', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='birthdate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='circle',
            name='supercircle',
            field=models.ForeignKey(default='Anchor Circle', on_delete=django.db.models.deletion.PROTECT, to='managetime.Circle'),
        ),
    ]
