# Generated by Django 2.0.5 on 2018-05-18 00:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managetime', '0004_auto_20180518_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='accountabilities',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='circle',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='circle',
            name='crosslinks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cross_link', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='circle',
            name='domains',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='circle',
            name='facilitator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fac_link', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='circle',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='circle',
            name='leadlink',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lead_link', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='circle',
            name='metrics',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='circle',
            name='objectives',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='circle',
            name='policies',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='circle',
            name='replink',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rep_link', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='circle',
            name='reports',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='circle',
            name='secretary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sec_link', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='circle',
            name='strategies',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
    ]
