# Generated by Django 2.0.5 on 2018-05-22 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managetime', '0005_auto_20180518_0024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membercommitment',
            options={'ordering': ['-deadline']},
        ),
        migrations.AddField(
            model_name='membercommitment',
            name='minuteestimate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membercommitment',
            name='timescheduled',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='membercommitment',
            name='whenworkday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membercommitment',
            name='whenworktime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='circle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='managetime.Circle'),
        ),
        migrations.AddField(
            model_name='task',
            name='doneevidence',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='managetime.Role'),
        ),
        migrations.AlterField(
            model_name='membercommitment',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='membercommitment',
            name='status',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='membercommitment',
            name='value',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='managetime.Project'),
        ),
    ]
