# Generated by Django 2.0.5 on 2018-05-25 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managetime', '0007_auto_20180524_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='created_by',
            field=models.CharField(default='jay', max_length=60),
            preserve_default=False,
        ),
    ]
