# Generated by Django 2.0.5 on 2018-05-26 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managetime', '0009_auto_20180526_0150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='projectcircle',
            new_name='circle',
        ),
        migrations.AddField(
            model_name='role',
            name='project',
            field=models.TextField(blank=True, max_length=60, null=True),
        ),
    ]
