# Generated by Django 2.0.5 on 2018-05-26 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managetime', '0010_auto_20180526_0155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='collaboartors',
        ),
        migrations.AddField(
            model_name='role',
            name='collaborators',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
