# Generated by Django 2.0.5 on 2018-05-27 01:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('managetime', '0011_auto_20180526_0202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kummitment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=600)),
                ('nextaction', models.TextField(max_length=600)),
                ('possibleobstacles', models.TextField(max_length=600)),
                ('minutesestimate', models.DurationField(blank=True, null=True)),
                ('start', models.DateTimeField(auto_now_add=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('timescheduled', models.TextField(blank=True, max_length=30, null=True)),
                ('energytype', models.TextField(blank=True, max_length=60, null=True)),
                ('workweek', models.TextField(blank=True, max_length=60, null=True)),
                ('workday', models.DateField(blank=True, null=True)),
                ('worktime', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=60, null=True)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('specific', models.BooleanField(default=0)),
                ('measurable', models.BooleanField(default=0)),
                ('achievable', models.BooleanField(default=0)),
                ('relevant', models.BooleanField(default=0)),
                ('timebound', models.BooleanField(default=0)),
                ('healthy', models.TextField(blank=True, max_length=600, null=True)),
                ('wealthy', models.TextField(blank=True, max_length=600, null=True)),
                ('wise', models.TextField(blank=True, max_length=600, null=True)),
                ('connected', models.TextField(max_length=600)),
                ('reflection', models.TextField(max_length=600)),
                ('needhelp', models.BooleanField(default=0)),
                ('kummitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='managetime.Task')),
            ],
            options={
                'ordering': ['-deadline'],
            },
        ),
        migrations.RenameModel(
            old_name='RoleCommitment',
            new_name='RoleKummitment',
        ),
        migrations.RemoveField(
            model_name='membercommitment',
            name='task',
        ),
        migrations.DeleteModel(
            name='MemberCommitment',
        ),
    ]
