# Generated by Django 2.0.5 on 2018-05-27 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managetime', '0012_auto_20180527_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kummitment',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
