# Generated by Django 2.0.5 on 2018-05-27 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managetime', '0014_auto_20180527_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kummitment',
            name='achievable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='kummitment',
            name='measurable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='kummitment',
            name='needhelp',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='kummitment',
            name='relevant',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='kummitment',
            name='specific',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='kummitment',
            name='timebound',
            field=models.BooleanField(default=False),
        ),
    ]
