# Generated by Django 2.0.5 on 2018-05-27 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managetime', '0015_auto_20180527_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='reports',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
    ]
