# Generated by Django 2.0.5 on 2018-05-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managetime', '0017_auto_20180528_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kummitment',
            name='reflection',
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
    ]
