# Generated by Django 2.0.5 on 2018-05-29 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managetime', '0019_kummitment_problemneedinghelp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kummitment',
            old_name='description',
            new_name='successactions',
        ),
    ]
